#!/usr/bin/env python3
"""Generate the TLC configurations of the models of work.mount.knullfs.4 and .7: the
RCU walk against vacate_mount() (MountWalk) and the vacant-mount protocol
(MntVacant)."""
import pathlib

# ---- MountWalk against vacate_mount(): the RCU walk into a vacated bind ----
# MountWalk.tla here is kernel/mount/MountWalk.tla plus the vacate change
MW_FIXES = ["FIX_RECHECK_MISS", "FIX_RECHECK_HOP", "FIX_RECHECK_DOTDOT", "FIX_SCOPED_EAGAIN", "FIX_RCU_FREE",
            "FIX_VACANT_CONNECTED", "FIX_DOTDOT_MSEQ"]
# the tree's state: every fix on but the m_seq alternative, which the tree does not have
MW_DEFAULT_OFF = {"FIX_DOTDOT_MSEQ"}
MW_SAFETY = ["NoUAF", "RcuResultOK", "ScopedOK", "Bounded", "Ledger"]
MW_SAFETY_VAC = MW_SAFETY + ["NoVacantEscape"]
# the root dentry of the mounts the mounter makes: the mounted filesystem's
# root, or a subdirectory of it (a bind mount) in the vacate layout
MW_NEWROOT = {"mountwalk": "F", "mountwalk3": "Fp"}
# name: (layout, change, victim, mounts, fixes flipped from the default, weak, invariants, expectation)
MW_CONFIGS = {
    # vacate_mount() against a walker inside a bind mount of a subdirectory:
    # with path_connected() trusting mnt_root the walker's ".." climbs out of
    # the bind into the filesystem it came from
    "mountwalk3_fixed_vacate":   ("mountwalk3", "vacate", 2, 1, [], False, MW_SAFETY_VAC, "pass"),
    "mountwalk3_no_vacant_connected": ("mountwalk3", "vacate", 2, 1, ["FIX_VACANT_CONNECTED"], False, MW_SAFETY, "violation: RcuResultOK, a walker that crossed into the bind before vacate_mount() climbs past the bind's root after it and returns -ENOENT from the filesystem underneath, where the walk succeeds at every instant"),
    "mountwalk3_dotdot_mseq":    ("mountwalk3", "vacate", 2, 1, ["FIX_VACANT_CONNECTED", "FIX_DOTDOT_MSEQ"], False, MW_SAFETY_VAC, "pass: an m_seq recheck after path_connected() closes it as well"),
    "mountwalk3_witness_vacant": ("mountwalk3", "vacate", 2, 1, ["FIX_VACANT_CONNECTED"], False, ["NoVacantEscape"], "violation"),
    "mountwalk3_fixed_umount":   ("mountwalk3", "umount", 2, 1, [], False, MW_SAFETY_VAC, "pass"),
    "mountwalk3_fixed_move":     ("mountwalk3", "move", 2, 1, [], False, MW_SAFETY_VAC, "pass"),
    "mountwalk_vacate_fullmount": ("mountwalk", "vacate", 2, 2, ["FIX_VACANT_CONNECTED"], False, MW_SAFETY_VAC, "pass: a mount of a whole filesystem has nothing above its root, so the stale root cannot be climbed past even without the fix"),
    # weakly ordered memory: vacate_mount()'s stores of mnt_sb and mnt_root
    # become visible in either order, and the loads follow_dotdot_rcu() and
    # path_connected() do without a recheck may each return the old or the
    # new value
    "mountwalk3_weak_vacate":    ("mountwalk3", "vacate", 2, 1, [], True, MW_SAFETY_VAC, "pass"),
    "mountwalk3_weak_no_vacant_connected": ("mountwalk3", "vacate", 2, 1, ["FIX_VACANT_CONNECTED"], True, MW_SAFETY, "violation: RcuResultOK"),
    "mountwalk3_weak_dotdot_mseq": ("mountwalk3", "vacate", 2, 1, ["FIX_VACANT_CONNECTED", "FIX_DOTDOT_MSEQ"], True, MW_SAFETY_VAC, "pass: the recheck's smp_rmb() orders the loads before the seqcount"),
    "mountwalk_weak_vacate_fullmount": ("mountwalk", "vacate", 2, 2, ["FIX_VACANT_CONNECTED"], True, MW_SAFETY_VAC, "pass"),
}
here = pathlib.Path(__file__).resolve().parent
for name, (layout, change, victim, mounts, flip, weak, invs, expect) in MW_CONFIGS.items():
    lines = [f"\\* generated by gen-cfgs.py: MountWalk ({layout}), expected: {expect}", "SPECIFICATION Spec", "CONSTANTS",
             "  Dentries <- DentriesDef", "  DParent <- DParentDef", "  DName <- DNameDef", "  DSb <- DSbDef", "  SbRoot <- SbRootDef",
             "  Negative <- NegativeDef", '  RootSb = "S"', '  NewSb = "F"', f'  NewRoot = "{MW_NEWROOT[layout]}"', '  NullSb = "N"',
             "  MntIds = {1, 2, 3}",
             '  Walkers = {"W1", "W2"}', "  WProg <- WProgDef", "  WRoot <- WRootDef", "  WScoped <- WScopedDef",
             "  MaxRestarts = 3", f"  Mounts = {mounts}", f'  CHANGE = "{change}"', f"  Victim = {victim}"]
    for f in MW_FIXES:
        on = (f not in MW_DEFAULT_OFF) != (f in flip)
        lines.append(f"  {f} = {'TRUE' if on else 'FALSE'}")
    lines.append(f"  WEAK_VACATE = {'TRUE' if weak else 'FALSE'}")
    lines.append("INVARIANTS")
    lines += [f"  {i}" for i in invs]
    (here / f"{name}.cfg").write_text("\n".join(lines) + "\n")


# ---- MntVacant: the vacant-mount protocol of work.mount.knullfs.4 ---------
VAC_FIXES = ["FIX_OWN_REF", "FIX_PUT_VACANT_ONLY", "FIX_TREE_ORDER", "FIX_DETACH_PUTS_VACANT", "FIX_DISOWNED",
             "FIX_HANDOFF_LOCKED", "FIX_LAST_UNDER_LOCK", "FIX_CONN_SB", "FIX_MARK_GATE"]
VAC_SAFETY = ["TypeOK", "NoNegative", "NoWarn", "ExactlyOnce", "NoDangling", "HashedHasRef", "DoomedIsLast",
              "OwnRefOnRing", "VacantCount", "VacantOK", "KnullfsOK", "NoVacantOnRing", "NoReveal", "NoHang",
              "NoNegativeWatch", "NoTeardownHang", "WatchedBalanced", "Reaped"]
VAC_OTHER = (("VACATE_MODE", '"vacate"'), ("DETACH_PUTS_ALL", "FALSE"), ("RELEASE_PUTS", "FALSE"),
             ("Marks", "FALSE"), ("U_INLINE", "FALSE"),
             ("NOREF", "FALSE"), ("NOREF_MARK", "TRUE"), ("NOREF_TRUST_MARK", "TRUE"), ("NOREF_SUM", "TRUE"),
             ("NOREF_HASHED_DOOMS", "FALSE"), ("NOREF_DETACH_FREES", "TRUE"))
# work.mount.knullfs.7: a stand-in has no reference of its own
NR = {"NOREF": "TRUE"}
NOREF_SAFETY = VAC_SAFETY + ["HeldCoversRefs", "NoOwnerPut"]
# name: (pins, holders, walk budget, detach targets, holder order, fixes off, other constants, invariants, expectation)
VAC_CONFIGS = {
    # the series: P held by a file, M held by a file, M's filesystem pins P and G's pins M,
    # a walker, rmdir of either mountpoint; every safety invariant, deadlock detection on
    "mntvacant_fixed":          (True,  ["H1", "H2"], 1, [2, 3], "any", [], {}, VAC_SAFETY, "pass"),
    "mntvacant_fixed_nopins":   (False, ["H1", "H2"], 1, [2, 3], "any", [], {}, VAC_SAFETY, "pass"),
    "mntvacant_fixed_walk2":    (True,  ["H1", "H2"], 2, [2, 3], "any", [], {}, VAC_SAFETY, "pass"),
    "mntvacant_fixed_noholder": (True,  [],           0, [2, 3], "any", [], {}, VAC_SAFETY, "pass"),
    # two walkers at once, from the file on P into M
    "mntvacant_fixed_2walkers": (True,  ["H1"],       1, [2],    "any", [], {"Walkers": '{"W1", "W2"}'}, VAC_SAFETY, "pass"),
    # the task-work shape of mntput_unmounted_work(): each final put's cleanup before the next put
    "mntvacant_fixed_inline":   (True,  ["H1", "H2"], 1, [2, 3], "any", [], {"U_INLINE": "TRUE"}, VAC_SAFETY, "pass"),
    # the earlier design: two references at vacate_mount(), the release ends in mntput()
    "mntvacant_count_two":      (True,  ["H1", "H2"], 1, [2, 3], "any", [], {"RELEASE_PUTS": "TRUE"}, VAC_SAFETY, "pass"),
    # upstream: the parent owns its attached unmounted children; with the
    # pins nothing is ever freed (Michael Vogt's cycle), without them it is fine
    "mntvacant_upstream":       (True,  ["H1"], 1, [2, 3], "any", ["FIX_OWN_REF"], {}, VAC_SAFETY, "violation: Reaped, M's filesystem pins P, P owns M"),
    "mntvacant_upstream_nopins": (False, ["H1", "H2"], 1, [2, 3], "any", ["FIX_OWN_REF"], {}, VAC_SAFETY, "pass"),
    # own references without vacate_mount(): the last put of an attached mount
    # dooms it in place (freed while hashed) or disconnects it (the reveal)
    "mntvacant_doom":           (False, ["H1"], 1, [], "any", [], {"VACATE_MODE": '"doom"'}, VAC_SAFETY, "violation: NoWarn (doomed_attached), HashedHasRef, NoHang or NoDangling"),
    "mntvacant_unhash":         (False, ["H1"], 1, [], "any", [], {"VACATE_MODE": '"unhash"'}, ["NoReveal"], "violation: NoReveal, a walk through the held parent lands in what the mount covered"),
    # the parent's final put putting every unhashed child while they hold their own reference
    "mntvacant_put_all":        (False, ["H1", "H2"], 1, [2, 3], "any", ["FIX_PUT_VACANT_ONLY"], {}, VAC_SAFETY, "violation: OwnRefOnRing, a child still holding its own reference is put by its parent's final put and vacated on the unmounted list; NoNegative later"),
    # __detach_mounts(): a vacant mount it unhashes must be put, and only a vacant one
    "mntvacant_detach_no_put":  (True,  ["H1"], 1, [2, 3], "any", ["FIX_DETACH_PUTS_VACANT"], {}, VAC_SAFETY, "violation: VacantCount, the parent's reference stays on a vacant mount nobody will put; Reaped later"),
    "mntvacant_detach_put_all": (True,  ["H1"], 1, [2, 3], "any", [], {"DETACH_PUTS_ALL": "TRUE"}, VAC_SAFETY, "violation: OwnRefOnRing, a mount still holding its own reference is put by __detach_mounts(); NoNegative later"),
    # a vacant mount riding the unmounted list instead of `disowned`: the
    # list's first mount carries the task work in the mnt_rcu its pending
    # release uses
    "mntvacant_ring_carrier":   (True,  ["H1"], 1, [2, 3], "any", ["FIX_DISOWNED"], {}, VAC_SAFETY, "violation: NoVacantOnRing"),
    "mntvacant_ring_carrier_lost": (True, ["H1"], 1, [2, 3], "any", ["FIX_DISOWNED"], {}, ["ExactlyOnce", "Reaped"], "violation: Reaped, the release the carrier clobbered never runs and the filesystem it would have released keeps its pin"),
    # the handoff decided after dropping mount_lock (the first draft)
    "mntvacant_handoff_unlocked": (True, ["H1", "H2"], 1, [2, 3], "any", ["FIX_HANDOFF_LOCKED"], {}, VAC_SAFETY, "violation: ExactlyOnce or NoWarn, both sides free or one uses the mount after the other freed it"),
    # the verdict of mntput_slow() from the flags re-read after unlock_mount_hash()
    # (the shape before the fixup): the parent's final put can cut and doom the
    # mount it just vacated in that window, and the vacating put frees it with
    # the release never queued
    "mntvacant_last_unlocked":  (True,  ["H1", "H2"], 1, [2, 3], "any", ["FIX_LAST_UNDER_LOCK"], {}, VAC_SAFETY, "violation: NoWarn (release_pending_at_free) or Reaped, the filesystem the mount carried is never released"),
    # the put order: parents first leaves a subtree nobody holds without vacant mounts
    "mntvacant_tree_order":     (False, [], 0, [], "any", [], {}, VAC_SAFETY + ["NoVacate"], "pass"),
    "mntvacant_lifo":           (False, [], 0, [], "any", ["FIX_TREE_ORDER"], {}, VAC_SAFETY + ["NoNeedlessVacate"], "violation: NoNeedlessVacate, children are put before their parent"),
    # dissolve_on_fput() and ksys_unshare(): the file's or fs_struct's reference on
    # the subtree root dropped before the puts leaves nothing to vacate; after them
    # every child is vacated
    "mntvacant_holder_early":   (False, ["H1"], 0, [], "early", [], {}, VAC_SAFETY + ["NoVacate"], "pass"),
    "mntvacant_holder_early_walk": (False, ["H1"], 1, [], "early", [], {}, ["NoVacate"], "violation: NoVacate, a walker that legitimized the dead parent keeps it alive while its child is put"),
    "mntvacant_holder_late":    (False, ["H1"], 1, [], "late", [], {}, VAC_SAFETY + ["NoVacate"], "violation: NoVacate"),
    # fsnotify: marks placed before a vacate are accounted on the superblock
    # the connector recorded and cleared by the release; knullfs takes none
    "mntvacant_marks":          (True,  ["H1", "H2"], 1, [2, 3], "any", [], {"Marks": "TRUE"}, VAC_SAFETY, "pass"),
    "mntvacant_marks_no_conn_sb": (True, ["H1", "H2"], 1, [2, 3], "any", ["FIX_CONN_SB"], {"Marks": "TRUE"}, VAC_SAFETY, "violation: NoNegativeWatch or NoTeardownHang, the mark of a vacated mount is taken back from knullfs and its old superblock waits in fsnotify_sb_delete() for good"),
    "mntvacant_marks_no_gate":  (True,  ["H1", "H2"], 1, [2, 3], "any", ["FIX_MARK_GATE"], {"Marks": "TRUE"}, VAC_SAFETY, "violation: NoWarn (free_marks) or WatchedBalanced, a mark placed on a vacant mount after its release is never cleared"),
    # witnesses: the interleavings the green runs cover do occur
    "mntvacant_witness_vacate":       (True, ["H1", "H2"], 1, [2, 3], "any", [], {}, ["NoVacate"], "violation"),
    "mntvacant_witness_walker_vacate": (True, ["H1", "H2"], 1, [2, 3], "any", [], {}, ["NoWalkerVacate"], "violation"),
    "mntvacant_witness_pin_doom":     (True, ["H1", "H2"], 1, [2, 3], "any", [], {}, ["NoPinDoom"], "violation"),
    "mntvacant_witness_put_first":    (True, ["H1", "H2"], 1, [2, 3], "any", [], {}, ["NoPutFirst"], "violation"),
    "mntvacant_witness_release_first": (True, ["H1", "H2"], 1, [2, 3], "any", [], {}, ["NoReleaseFirst"], "violation"),
    "mntvacant_witness_detach_put":   (True, ["H1", "H2"], 1, [2, 3], "any", [], {}, ["NoDetachPut"], "violation"),
    "mntvacant_witness_null_seen":    (True, ["H1", "H2"], 1, [2, 3], "any", [], {}, ["NoNullSeen"], "violation: NoNullSeen, a walk through the held parent lands on the knullfs directory that stands in for the vacated mount"),
    "mntvacant_witness_mark_refused": (True, ["H1", "H2"], 1, [2, 3], "any", [], {"Marks": "TRUE"}, ["NoMarkRefused"], "violation: NoMarkRefused, fanotify refuses a mount mark on the stand-in"),
    # an RCU walker inside a mount while the filesystem it carried is torn
    # down: the series through vacate_mount()'s release, upstream through
    # the stuck children of the parent's final put; neither waits for a
    # grace period, the RCU-pathwalk contract covers both
    "mntvacant_witness_rcu_teardown": (True, ["H1", "H2"], 1, [2, 3], "any", [], {}, ["NoRcuTeardown"], "violation"),
    "mntvacant_witness_rcu_teardown_upstream": (False, ["H1"], 1, [2, 3], "any", ["FIX_OWN_REF"], {}, ["NoRcuTeardown"], "violation"),
    # work.mount.knullfs.7: no reference for the parent; __legitimize_mnt() marks
    # the stand-in, the parent frees an unmarked one without a sum and sums a
    # marked one, a walk's last put leaves a hashed stand-in at zero
    "mntvacant_noref":          (True,  ["H1", "H2"], 1, [2, 3], "any", [], NR, NOREF_SAFETY, "pass"),
    "mntvacant_noref_nopins":   (False, ["H1", "H2"], 1, [2, 3], "any", [], NR, NOREF_SAFETY, "pass"),
    "mntvacant_noref_noholder": (True,  [],           0, [2, 3], "any", [], NR, NOREF_SAFETY, "pass"),
    "mntvacant_noref_walk2":    (True,  ["H1", "H2"], 2, [2, 3], "any", [], NR, NOREF_SAFETY, "pass"),
    "mntvacant_noref_2walkers": (True,  ["H1"],       1, [2],    "any", [], NR | {"Walkers": '{"W1", "W2"}'}, NOREF_SAFETY, "pass"),
    "mntvacant_noref_inline":   (True,  ["H1", "H2"], 1, [2, 3], "any", [], NR | {"U_INLINE": "TRUE"}, NOREF_SAFETY, "pass"),
    "mntvacant_noref_marks":    (True,  ["H1", "H2"], 1, [2, 3], "any", [], NR | {"Marks": "TRUE"}, NOREF_SAFETY, "pass"),
    # the count alone decides (no mark at all): right under sequential
    # consistency, the mark only saves the sum
    "mntvacant_noref_sum_only": (True,  ["H1", "H2"], 1, [2, 3], "any", [], NR | {"NOREF_MARK": "FALSE", "NOREF_TRUST_MARK": "FALSE"}, VAC_SAFETY + ["NoOwnerPut"], "pass"),
    # the walk does not mark the stand-in it holds and the parent trusts the mark
    "mntvacant_noref_no_mark":  (True,  ["H1", "H2"], 1, [2, 3], "any", [], NR | {"NOREF_MARK": "FALSE"}, NOREF_SAFETY, "violation: NoDangling or NoWarn, the parent frees a stand-in a walk still holds"),
    # the parent never sums: a marked stand-in whose walk is gone is never freed
    "mntvacant_noref_no_sum":   (True,  ["H1", "H2"], 1, [2, 3], "any", [], NR | {"NOREF_SUM": "FALSE"}, NOREF_SAFETY, "violation: Reaped, a marked stand-in nobody holds anymore is disowned but never freed"),
    # a walk's last put dooms a stand-in that is still hashed
    "mntvacant_noref_hashed_dooms": (True, ["H1", "H2"], 1, [2, 3], "any", [], NR | {"NOREF_HASHED_DOOMS": "TRUE"}, NOREF_SAFETY, "violation: HashedHasRef, NoHang or NoDangling, a doomed stand-in stays in the hash"),
    # __detach_mounts() cuts a dead stand-in loose without freeing it
    "mntvacant_noref_detach_leak": (True, ["H1", "H2"], 1, [2, 3], "any", [], NR | {"NOREF_DETACH_FREES": "FALSE"}, NOREF_SAFETY, "violation: Reaped"),
    # witnesses: the parent and __detach_mounts() do free stand-ins without a
    # put, a walk's last put does leave a hashed stand-in at zero, and the
    # handoff with the release runs both ways
    "mntvacant_noref_witness_dead_free":   (True, ["H1", "H2"], 1, [2, 3], "any", [], NR, ["NoDeadFree"], "violation"),
    "mntvacant_noref_witness_hashed_zero": (True, ["H1", "H2"], 1, [2, 3], "any", [], NR, ["NoHashedZero"], "violation"),
    "mntvacant_noref_witness_put_first":   (True, ["H1", "H2"], 1, [2, 3], "any", [], NR, ["NoPutFirst"], "violation"),
    "mntvacant_noref_witness_release_first": (True, ["H1", "H2"], 1, [2, 3], "any", [], NR, ["NoReleaseFirst"], "violation"),
}
for name, (pins, holders, budget, targets, order, off, other, invs, expect) in VAC_CONFIGS.items():
    lines = [f"\\* generated by gen-cfgs.py: MntVacant, expected: {expect}", "SPECIFICATION Spec", "CONSTANTS",
             "  MntIds = {1, 2, 3}", "  Parent <- ParentDef", '  SbIds = {"p", "m", "g"}', "  Sb <- SbDef", '  NullSb = "n"',
             f"  Pin <- {'PinDef' if pins else 'NoPinDef'}",
             "  Holders = {" + ", ".join(f'"{h}"' for h in holders) + "}", "  HolderMnt <- HolderMntDef",
             "  Walkers = " + other.get("Walkers", '{"W1"}'), f"  WalkBudget = {budget}",
             "  DetachTargets = {" + ", ".join(str(t) for t in targets) + "}",
             f'  HOLDER_ORDER = "{order}"']
    for f in VAC_FIXES:
        lines.append(f"  {f} = {'FALSE' if f in off else 'TRUE'}")
    for c, default in VAC_OTHER:
        lines.append(f"  {c} = {other.get(c, default)}")
    lines.append("INVARIANTS")
    lines += [f"  {i}" for i in invs]
    pathlib.Path(__file__).resolve().parent.joinpath(name + ".cfg").write_text("\n".join(lines) + "\n")

print(f"{len(MW_CONFIGS) + len(VAC_CONFIGS)} configurations written")
