---------------------------- MODULE MC_dtsharefz ----------------------------
(* The layout for SuperDevTable: s1 on d1 with extra member d2 (refused -> the mount fails), s2 on d2, nobody unmounts; a freezer on d2. *)
(* Generated by gen-cfgs.py. *)
EXTENDS SuperDevTable, TLC

DevsDef == {"d1", "d2"}
SbsDef == {"s1", "s2"}
FsCfgDef == ("s1" :> [main |-> "d1", xmode |-> "mount", xdev |-> "d2", onfail |-> "fail", dropx |-> "no", umount |-> FALSE, mayfail |-> FALSE]) @@ ("s2" :> [main |-> "d2", xmode |-> "none", xdev |-> "d1", onfail |-> "fail", dropx |-> "no", umount |-> FALSE, mayfail |-> FALSE])
FreezersDef == ("F2" :> "d2")
CursorsDef == [x \in {} |-> "none"]
DupsDef == [x \in {} |-> [sb |-> "none", after |-> FALSE]]
=============================================================================
