---------------------------- MODULE MC_dtmultideg ----------------------------
(* The layout for SuperDevTable: s1 on d1 with extra member d2, refused -> the mount goes on (btrfs -o degraded); a freezer on d1 and one on d2. *)
(* Generated by gen-cfgs.py. *)
EXTENDS SuperDevTable, TLC

DevsDef == {"d1", "d2"}
SbsDef == {"s1"}
FsCfgDef == ("s1" :> [main |-> "d1", xmode |-> "mount", xdev |-> "d2", onfail |-> "degraded", dropx |-> "no", umount |-> FALSE, mayfail |-> FALSE])
FreezersDef == ("F1" :> "d1") @@ ("F2" :> "d2")
CursorsDef == [x \in {} |-> "none"]
DupsDef == [x \in {} |-> [sb |-> "none", after |-> FALSE]]
=============================================================================
