---------------------------- MODULE MC_dtdup ----------------------------
(* The layout for SuperDevTable: s1 on d1 with extra member d2 accepted and released before SB_BORN, plus a second concurrent fs_bdev_register()/fs_bdev_unregister() of (d2, s1). *)
(* Generated by gen-cfgs.py. *)
EXTENDS SuperDevTable, TLC

DevsDef == {"d1", "d2"}
SbsDef == {"s1"}
FsCfgDef == ("s1" :> [main |-> "d1", xmode |-> "mount", xdev |-> "d2", onfail |-> "fail", dropx |-> "early", umount |-> FALSE, mayfail |-> FALSE])
FreezersDef == [x \in {} |-> "none"]
CursorsDef == [x \in {} |-> "none"]
DupsDef == ("D1" :> [sb |-> "s1", after |-> FALSE])
=============================================================================
