---------------------------- MODULE MC_dtreadd ----------------------------
(* The layout for SuperDevTable: s1 on d1 with extra member d2 accepted and released before SB_BORN, then registered and released again by another task (a re-add). *)
(* Generated by gen-cfgs.py. *)
EXTENDS SuperDevTable, TLC

DevsDef == {"d1", "d2"}
SbsDef == {"s1"}
FsCfgDef == ("s1" :> [main |-> "d1", xmode |-> "mount", xdev |-> "d2", onfail |-> "fail", dropx |-> "early", umount |-> FALSE, mayfail |-> FALSE])
FreezersDef == [x \in {} |-> "none"]
CursorsDef == [x \in {} |-> "none"]
DupsDef == ("D1" :> [sb |-> "s1", after |-> TRUE])
=============================================================================
