---------------------------- MODULE MC_dtshare ----------------------------
(* The layout for SuperDevTable: s1 on d1 with extra member d2 registered during the mount (refused -> the mount fails), s2 on d2; both unmounted; a freezer and a cursor on d2. *)
(* Generated by gen-cfgs.py. *)
EXTENDS SuperDevTable, TLC

DevsDef == {"d1", "d2"}
SbsDef == {"s1", "s2"}
FsCfgDef == ("s1" :> [main |-> "d1", xmode |-> "mount", xdev |-> "d2", onfail |-> "fail", dropx |-> "no", umount |-> TRUE, mayfail |-> FALSE]) @@ ("s2" :> [main |-> "d2", xmode |-> "none", xdev |-> "d1", onfail |-> "fail", dropx |-> "no", umount |-> TRUE, mayfail |-> FALSE])
FreezersDef == ("F2" :> "d2")
CursorsDef == ("C2" :> "d2")
DupsDef == [x \in {} |-> [sb |-> "none", after |-> FALSE]]
=============================================================================
