---------------------------- MODULE MC_dtlive ----------------------------
(* The layout for SuperDevTable: s1 on d1, d2 added to the live superblock and removed again (btrfs device add/remove under bdev_deny_freeze()), unmounted; a freezer on d2. *)
(* Generated by gen-cfgs.py. *)
EXTENDS SuperDevTable, TLC

DevsDef == {"d1", "d2"}
SbsDef == {"s1"}
FsCfgDef == ("s1" :> [main |-> "d1", xmode |-> "live", xdev |-> "d2", onfail |-> "fail", dropx |-> "live", umount |-> TRUE, mayfail |-> FALSE])
FreezersDef == ("F2" :> "d2")
CursorsDef == [x \in {} |-> "none"]
DupsDef == [x \in {} |-> [sb |-> "none", after |-> FALSE]]
=============================================================================
