---------------------------- MODULE MC_dtwalk ----------------------------
(* The layout for SuperDevTable: s1 on d1 with extra member d2 (refused -> the mount fails) and s2 on d2, both unmounted, mount of s2 may fail; two user_get_super() cursors on d2. *)
(* Generated by gen-cfgs.py. *)
EXTENDS SuperDevTable, TLC

DevsDef == {"d1", "d2"}
SbsDef == {"s1", "s2"}
FsCfgDef == ("s1" :> [main |-> "d1", xmode |-> "mount", xdev |-> "d2", onfail |-> "fail", dropx |-> "no", umount |-> TRUE, mayfail |-> FALSE]) @@ ("s2" :> [main |-> "d2", xmode |-> "none", xdev |-> "d1", onfail |-> "fail", dropx |-> "no", umount |-> TRUE, mayfail |-> TRUE])
FreezersDef == [x \in {} |-> "none"]
CursorsDef == ("C1" :> "d2") @@ ("C2" :> "d2")
DupsDef == [x \in {} |-> [sb |-> "none", after |-> FALSE]]
=============================================================================
