---------------------------- MODULE MC_dtbase ----------------------------
(* The layout for SuperDevTable: s1 on d1 (sget entry + setup_bdev_super claim), mount may fail, unmounted; a freezer and a user_get_super() cursor on d1. *)
(* Generated by gen-cfgs.py. *)
EXTENDS SuperDevTable, TLC

DevsDef == {"d1"}
SbsDef == {"s1"}
FsCfgDef == ("s1" :> [main |-> "d1", xmode |-> "none", xdev |-> "d2", onfail |-> "fail", dropx |-> "no", umount |-> TRUE, mayfail |-> TRUE])
FreezersDef == ("F1" :> "d1")
CursorsDef == ("C1" :> "d1")
DupsDef == [x \in {} |-> [sb |-> "none", after |-> FALSE]]
=============================================================================
