---------------------------- MODULE MC_dtdrop ----------------------------
(* The layout for SuperDevTable: s1 on d1 with extra member d2 accepted during the mount and released again before SB_BORN while the mount goes on (btrfs __btrfs_free_extra_devids()); a freezer on d2. *)
(* Generated by gen-cfgs.py. *)
EXTENDS SuperDevTable, TLC

DevsDef == {"d1", "d2"}
SbsDef == {"s1"}
FsCfgDef == ("s1" :> [main |-> "d1", xmode |-> "mount", xdev |-> "d2", onfail |-> "fail", dropx |-> "early", umount |-> FALSE, mayfail |-> FALSE])
FreezersDef == ("F2" :> "d2")
CursorsDef == [x \in {} |-> "none"]
DupsDef == [x \in {} |-> [sb |-> "none", after |-> FALSE]]
=============================================================================
