#!/usr/bin/env python3
"""Generate the TLC configurations of the models of work.mount.knullfs.7.order:
the RCU walk against vacate_mount() (MountWalk, as in kernel/mount-knullfs), the
vacant-mount protocol without a reference for the stand-in (MntVacant, NOREF,
with the mark and the increment of __legitimize_mnt() as buffered stores) and
the propagation algebra with the series' propagate_umount() (Propagation and
MountOps, the fork of kernel/mount)."""
import pathlib

# ---- MountWalk against vacate_mount(): the RCU walk into a vacated bind ----
# MountWalk.tla here is kernel/mount/MountWalk.tla plus the vacate change
MW_FIXES = ["FIX_RECHECK_MISS", "FIX_RECHECK_HOP", "FIX_RECHECK_DOTDOT", "FIX_SCOPED_EAGAIN", "FIX_RCU_FREE",
            "FIX_VACANT_CONNECTED", "FIX_DOTDOT_MSEQ"]
# the tree's state: every fix on but the m_seq alternative, which the tree does not have
MW_DEFAULT_OFF = {"FIX_DOTDOT_MSEQ"}
MW_SAFETY = ["NoUAF", "RcuResultOK", "ScopedOK", "Bounded", "Ledger"]
MW_SAFETY_VAC = MW_SAFETY + ["NoVacantEscape"]
# the root dentry of the mounts the mounter makes: the mounted filesystem's
# root, or a subdirectory of it (a bind mount) in the vacate layout
MW_NEWROOT = {"mountwalk": "F", "mountwalk3": "Fp"}
# name: (layout, change, victim, mounts, fixes flipped from the default, weak, invariants, expectation)
MW_CONFIGS = {
    # vacate_mount() against a walker inside a bind mount of a subdirectory:
    # with path_connected() trusting mnt_root the walker's ".." climbs out of
    # the bind into the filesystem it came from
    "mountwalk3_fixed_vacate":   ("mountwalk3", "vacate", 2, 1, [], False, MW_SAFETY_VAC, "pass"),
    "mountwalk3_no_vacant_connected": ("mountwalk3", "vacate", 2, 1, ["FIX_VACANT_CONNECTED"], False, MW_SAFETY, "violation: RcuResultOK, a walker that crossed into the bind before vacate_mount() climbs past the bind's root after it and returns -ENOENT from the filesystem underneath, where the walk succeeds at every instant"),
    "mountwalk3_dotdot_mseq":    ("mountwalk3", "vacate", 2, 1, ["FIX_VACANT_CONNECTED", "FIX_DOTDOT_MSEQ"], False, MW_SAFETY_VAC, "pass: an m_seq recheck after path_connected() closes it as well"),
    "mountwalk3_witness_vacant": ("mountwalk3", "vacate", 2, 1, ["FIX_VACANT_CONNECTED"], False, ["NoVacantEscape"], "violation"),
    "mountwalk3_fixed_umount":   ("mountwalk3", "umount", 2, 1, [], False, MW_SAFETY_VAC, "pass"),
    "mountwalk3_fixed_move":     ("mountwalk3", "move", 2, 1, [], False, MW_SAFETY_VAC, "pass"),
    "mountwalk_vacate_fullmount": ("mountwalk", "vacate", 2, 2, ["FIX_VACANT_CONNECTED"], False, MW_SAFETY_VAC, "pass: a mount of a whole filesystem has nothing above its root, so the stale root cannot be climbed past even without the fix"),
    # weakly ordered memory: vacate_mount()'s stores of mnt_sb and mnt_root
    # become visible in either order, and the loads follow_dotdot_rcu() and
    # path_connected() do without a recheck may each return the old or the
    # new value
    "mountwalk3_weak_vacate":    ("mountwalk3", "vacate", 2, 1, [], True, MW_SAFETY_VAC, "pass"),
    "mountwalk3_weak_no_vacant_connected": ("mountwalk3", "vacate", 2, 1, ["FIX_VACANT_CONNECTED"], True, MW_SAFETY, "violation: RcuResultOK"),
    "mountwalk3_weak_dotdot_mseq": ("mountwalk3", "vacate", 2, 1, ["FIX_VACANT_CONNECTED", "FIX_DOTDOT_MSEQ"], True, MW_SAFETY_VAC, "pass: the recheck's smp_rmb() orders the loads before the seqcount"),
    "mountwalk_weak_vacate_fullmount": ("mountwalk", "vacate", 2, 2, ["FIX_VACANT_CONNECTED"], True, MW_SAFETY_VAC, "pass"),
}
here = pathlib.Path(__file__).resolve().parent
for name, (layout, change, victim, mounts, flip, weak, invs, expect) in MW_CONFIGS.items():
    lines = [f"\\* generated by gen-cfgs.py: MountWalk ({layout}), expected: {expect}", "SPECIFICATION Spec", "CONSTANTS",
             "  Dentries <- DentriesDef", "  DParent <- DParentDef", "  DName <- DNameDef", "  DSb <- DSbDef", "  SbRoot <- SbRootDef",
             "  Negative <- NegativeDef", '  RootSb = "S"', '  NewSb = "F"', f'  NewRoot = "{MW_NEWROOT[layout]}"', '  NullSb = "N"',
             "  MntIds = {1, 2, 3}",
             '  Walkers = {"W1", "W2"}', "  WProg <- WProgDef", "  WRoot <- WRootDef", "  WScoped <- WScopedDef",
             "  MaxRestarts = 3", f"  Mounts = {mounts}", f'  CHANGE = "{change}"', f"  Victim = {victim}"]
    for f in MW_FIXES:
        on = (f not in MW_DEFAULT_OFF) != (f in flip)
        lines.append(f"  {f} = {'TRUE' if on else 'FALSE'}")
    lines.append(f"  WEAK_VACATE = {'TRUE' if weak else 'FALSE'}")
    lines.append("INVARIANTS")
    lines += [f"  {i}" for i in invs]
    (here / f"{name}.cfg").write_text("\n".join(lines) + "\n")


# ---- MntVacant: the vacant-mount protocol, NOREF (work.mount.knullfs.7 and .7.order) ---------
VAC_FIXES = ["FIX_OWN_REF", "FIX_PUT_VACANT_ONLY", "FIX_TREE_ORDER", "FIX_DETACH_PUTS_VACANT", "FIX_DISOWNED",
             "FIX_HANDOFF_LOCKED", "FIX_LAST_UNDER_LOCK", "FIX_CONN_SB", "FIX_MARK_GATE"]
VAC_SAFETY = ["TypeOK", "NoNegative", "NoWarn", "ExactlyOnce", "NoDangling", "HashedHasRef", "DoomedIsLast",
              "OwnRefOnRing", "VacantCount", "VacantOK", "KnullfsOK", "NoVacantOnRing", "NoReveal", "NoHang",
              "NoNegativeWatch", "NoTeardownHang", "WatchedBalanced", "Reaped"]
VAC_OTHER = (("VACATE_MODE", '"vacate"'), ("DETACH_PUTS_ALL", "FALSE"), ("RELEASE_PUTS", "FALSE"),
             ("Marks", "FALSE"), ("U_INLINE", "FALSE"),
             ("NOREF", "FALSE"), ("NOREF_MARK", "TRUE"), ("NOREF_TRUST_MARK", "TRUE"), ("NOREF_SUM", "TRUE"),
             ("NOREF_HASHED_DOOMS", "FALSE"), ("NOREF_DETACH_FREES", "TRUE"),
             ("MARK_STORES", '"sc"'), ("FIX_LOCK_DOOMED", "TRUE"))
# work.mount.knullfs.7: a stand-in has no reference of its own
NR = {"NOREF": "TRUE"}
NOREF_SAFETY = VAC_SAFETY + ["HeldCoversRefs", "NoOwnerPut"]
# the fast path's mark and increment as buffered stores, in program order or in either order
NRT = NR | {"MARK_STORES": '"tso"'}
NRW = NR | {"MARK_STORES": '"weak"'}
# name: (pins, holders, walk budget, detach targets, holder order, fixes off, other constants, invariants, expectation)
VAC_CONFIGS = {
    # the .4 mode through the edited module: kernel/mount-knullfs's count, the additions leave it untouched
    "mntvacant_fixed":          (True,  ["H1", "H2"], 1, [2, 3], "any", [], {}, VAC_SAFETY, "pass"),
    # work.mount.knullfs.7: no reference for the parent; __legitimize_mnt() marks
    # the stand-in, the parent frees an unmarked one without a sum and sums a
    # marked one, a walk's last put leaves a hashed stand-in at zero
    "mntvacant_noref":          (True,  ["H1", "H2"], 1, [2, 3], "any", [], NR, NOREF_SAFETY, "pass"),
    "mntvacant_noref_nopins":   (False, ["H1", "H2"], 1, [2, 3], "any", [], NR, NOREF_SAFETY, "pass"),
    "mntvacant_noref_noholder": (True,  [],           0, [2, 3], "any", [], NR, NOREF_SAFETY, "pass"),
    "mntvacant_noref_walk2":    (True,  ["H1", "H2"], 2, [2, 3], "any", [], NR, NOREF_SAFETY, "pass"),
    "mntvacant_noref_2walkers": (True,  ["H1"],       1, [2],    "any", [], NR | {"Walkers": '{"W1", "W2"}'}, NOREF_SAFETY, "pass"),
    "mntvacant_noref_inline":   (True,  ["H1", "H2"], 1, [2, 3], "any", [], NR | {"U_INLINE": "TRUE"}, NOREF_SAFETY, "pass"),
    "mntvacant_noref_marks":    (True,  ["H1", "H2"], 1, [2, 3], "any", [], NR | {"Marks": "TRUE"}, NOREF_SAFETY, "pass"),
    # the count alone decides (no mark at all): right under sequential
    # consistency, the mark only saves the sum
    "mntvacant_noref_sum_only": (True,  ["H1", "H2"], 1, [2, 3], "any", [], NR | {"NOREF_MARK": "FALSE", "NOREF_TRUST_MARK": "FALSE"}, VAC_SAFETY + ["NoOwnerPut"], "pass"),
    # the walk does not mark the stand-in it holds and the parent trusts the mark
    "mntvacant_noref_no_mark":  (True,  ["H1", "H2"], 1, [2, 3], "any", [], NR | {"NOREF_MARK": "FALSE"}, NOREF_SAFETY, "violation: NoDangling or NoWarn, the parent frees a stand-in a walk still holds"),
    # the parent never sums: a marked stand-in whose walk is gone is never freed
    "mntvacant_noref_no_sum":   (True,  ["H1", "H2"], 1, [2, 3], "any", [], NR | {"NOREF_SUM": "FALSE"}, NOREF_SAFETY, "violation: Reaped, a marked stand-in nobody holds anymore is disowned but never freed"),
    # a walk's last put dooms a stand-in that is still hashed
    "mntvacant_noref_hashed_dooms": (True, ["H1", "H2"], 1, [2, 3], "any", [], NR | {"NOREF_HASHED_DOOMS": "TRUE"}, NOREF_SAFETY, "violation: HashedHasRef, NoHang or NoDangling, a doomed stand-in stays in the hash"),
    # __detach_mounts() cuts a dead stand-in loose without freeing it
    "mntvacant_noref_detach_leak": (True, ["H1", "H2"], 1, [2, 3], "any", [], NR | {"NOREF_DETACH_FREES": "FALSE"}, NOREF_SAFETY, "violation: Reaped"),
    # witnesses: the parent and __detach_mounts() do free stand-ins without a
    # put, a walk's last put does leave a hashed stand-in at zero, and the
    # handoff with the release runs both ways
    "mntvacant_noref_witness_dead_free":   (True, ["H1", "H2"], 1, [2, 3], "any", [], NR, ["NoDeadFree"], "violation"),
    "mntvacant_noref_witness_hashed_zero": (True, ["H1", "H2"], 1, [2, 3], "any", [], NR, ["NoHashedZero"], "violation"),
    "mntvacant_noref_witness_put_first":   (True, ["H1", "H2"], 1, [2, 3], "any", [], NR, ["NoPutFirst"], "violation"),
    "mntvacant_noref_witness_release_first": (True, ["H1", "H2"], 1, [2, 3], "any", [], NR, ["NoReleaseFirst"], "violation"),
    # work.mount.knullfs.7.order keeps the protocol; the mark and the increment
    # of __legitimize_mnt()'s fast path as separate stores in the walker's
    # store buffer, in program order (tso) or in either order (weak): the
    # verdict of the parent or of __detach_mounts() can land between the first
    # read_seqretry() and the stores, or between the stores
    "mntvacant_noref_tso":          (True,  ["H1", "H2"], 1, [2, 3], "any", [], NRT, NOREF_SAFETY, "pass"),
    "mntvacant_noref_weak":         (True,  ["H1", "H2"], 1, [2, 3], "any", [], NRW, NOREF_SAFETY, "pass"),
    "mntvacant_noref_weak_nopins":  (False, ["H1", "H2"], 1, [2, 3], "any", [], NRW, NOREF_SAFETY, "pass"),
    "mntvacant_noref_weak_walk2":   (True,  ["H1", "H2"], 2, [2, 3], "any", [], NRW, NOREF_SAFETY, "pass"),
    "mntvacant_noref_weak_2walkers": (True, ["H1"],       1, [2],    "any", [], NRW | {"Walkers": '{"W1", "W2"}'}, NOREF_SAFETY, "pass"),
    "mntvacant_noref_weak_inline":  (True,  ["H1", "H2"], 1, [2, 3], "any", [], NRW | {"U_INLINE": "TRUE"}, NOREF_SAFETY, "pass"),
    "mntvacant_noref_weak_no_mark": (True,  ["H1", "H2"], 1, [2, 3], "any", [], NRW | {"NOREF_MARK": "FALSE"}, NOREF_SAFETY, "violation: NoDangling or NoWarn, the parent frees a stand-in a walk still holds"),
    # the lock_mount_hash() path of __legitimize_mnt() without mainline's
    # MNT_DOOMED check: a verdict of dead between the first read_seqretry()
    # and the walker's stores dooms and frees the stand-in, and the walker's
    # mntput() of its increment, outside rcu_read_lock(), frees it again
    # (DoomedIsLast catches the increment left on the doomed stand-in one step
    # earlier; these run the memory-safety invariants alone to reach the free)
    "mntvacant_noref_weak_no_lock_doomed": (True, ["H1", "H2"], 1, [2, 3], "any", [], NRW | {"FIX_LOCK_DOOMED": "FALSE"}, ["NoDangling", "NoWarn", "ExactlyOnce", "Reaped"], "violation: NoDangling or NoWarn (put_doomed, double_free), the walker's mntput() reaches a stand-in the release freed"),
    "mntvacant_noref_tso_no_lock_doomed":  (True, ["H1", "H2"], 1, [2, 3], "any", [], NRT | {"FIX_LOCK_DOOMED": "FALSE"}, ["NoDangling", "NoWarn", "ExactlyOnce", "Reaped"], "violation: NoDangling or NoWarn (put_doomed, double_free), the walker's mntput() reaches a stand-in the release freed"),
    "mntvacant_noref_tso_no_lock_doomed_last": (True, ["H1", "H2"], 1, [2, 3], "any", [], NRT | {"FIX_LOCK_DOOMED": "FALSE"}, NOREF_SAFETY, "violation: DoomedIsLast, the walker keeps an increment on the doomed stand-in that the lock path should have taken back"),
    "mntvacant_noref_weak_no_lock_doomed_uaf": (True, ["H1", "H2"], 1, [2, 3], "any", [], NRW | {"FIX_LOCK_DOOMED": "FALSE"}, ["NoDangling", "ExactlyOnce", "Reaped"], "violation: NoDangling, the release frees the doomed stand-in and its RCU callback runs once the walker left its read section, before the walker's mntput()"),
    "mntvacant_noref_sc_no_lock_doomed":   (True, ["H1", "H2"], 1, [2, 3], "any", [], NR | {"FIX_LOCK_DOOMED": "FALSE"}, NOREF_SAFETY, "pass: with the first read_seqretry(), the mark and the increment in one step no verdict lands in between, so the window the check closes is invisible to the sequentially consistent model"),
    # witnesses: a verdict does land while a walker's stores are buffered, and
    # the lock_mount_hash() path does take an increment back from a doomed stand-in
    "mntvacant_noref_weak_witness_split":   (True, ["H1", "H2"], 1, [2, 3], "any", [], NRW, ["NoSplit"], "violation"),
    "mntvacant_noref_weak_witness_phantom": (True, ["H1", "H2"], 1, [2, 3], "any", [], NRW, ["NoPhantom"], "violation"),
    "mntvacant_noref_tso_witness_phantom":  (True, ["H1", "H2"], 1, [2, 3], "any", [], NRT, ["NoPhantom"], "violation"),
    "mntvacant_noref_sc_witness_phantom":   (True, ["H1", "H2"], 1, [2, 3], "any", [], NR, ["NoPhantom"], "pass: the one-step fast path never meets a verdict"),
}
for name, (pins, holders, budget, targets, order, off, other, invs, expect) in VAC_CONFIGS.items():
    lines = [f"\\* generated by gen-cfgs.py: MntVacant, expected: {expect}", "SPECIFICATION Spec", "CONSTANTS",
             "  MntIds = {1, 2, 3}", "  Parent <- ParentDef", '  SbIds = {"p", "m", "g"}', "  Sb <- SbDef", '  NullSb = "n"',
             f"  Pin <- {'PinDef' if pins else 'NoPinDef'}",
             "  Holders = {" + ", ".join(f'"{h}"' for h in holders) + "}", "  HolderMnt <- HolderMntDef",
             "  Walkers = " + other.get("Walkers", '{"W1"}'), f"  WalkBudget = {budget}",
             "  DetachTargets = {" + ", ".join(str(t) for t in targets) + "}",
             f'  HOLDER_ORDER = "{order}"']
    for f in VAC_FIXES:
        lines.append(f"  {f} = {'FALSE' if f in off else 'TRUE'}")
    for c, default in VAC_OTHER:
        lines.append(f"  {c} = {other.get(c, default)}")
    lines.append("INVARIANTS")
    lines += [f"  {i}" for i in invs]
    pathlib.Path(__file__).resolve().parent.joinpath(name + ".cfg").write_text("\n".join(lines) + "\n")


# ---- the propagation algebra with the series' propagate_umount() ----------
# Propagation.tla and MountOps.tla here are kernel/mount's plus KEEP_LINKED,
# ROOT_BY_ROOT and TRACK_UNDECIDED (the prep "namespace: let propagate_umount()
# hand the set back root by root"); the layouts are kernel/mount's plus two
# scripted ones
PROP_FIXES = ["FIX_TRIM_ANCESTORS", "FIX_HANDLE_LOCKED", "FIX_REPARENT_LATE",
              "FIX_FIND_MASTER_STOP", "FIX_TUCK_LOCK", "FIX_PUT_MNT_NS_DISCONNECT",
              "FIX_CLONE_UNBINDABLE", "FIX_SET_GROUP_UNBINDABLE", "FIX_BUSY_VICTIMS"]
PROP_MAINLINE_SAFETY = ["TypeOK", "AlgebraOK", "Structure", "IteratorsOK", "NsOK", "RefsOK",
                        "CoverOK", "SyncUmountNotBusy", "BusyMirrorOK", "DeadUnderDead"]
PROP_SAFETY = PROP_MAINLINE_SAFETY + ["HandbackOK"]
PROP_LAYOUTS = {  # name: (mount ids, namespace ids, MaxOps, MaxFds)
    "small": (6, 3, 4, 1), "chain": (10, 3, 3, 1), "peers": (8, 3, 3, 1), "locked": (9, 3, 3, 1),
    "parentcand": (6, 2, 1, 1),   # scripted: the victim's parent is a candidate itself
    "crossbind": (9, 2, 1, 1),    # scripted: a candidate above a candidate discovered after it
    "propns": (9, 3, 1, 1),       # scripted: a propagated copy with a child
}
SERIES = {"KEEP_LINKED": "TRUE", "ROOT_BY_ROOT": "TRUE", "TRACK_UNDECIDED": "TRUE"}
MAINLINE = {"KEEP_LINKED": "FALSE", "ROOT_BY_ROOT": "FALSE", "TRACK_UNDECIDED": "TRUE"}
KEEP_SPLICE = {"KEEP_LINKED": "TRUE", "ROOT_BY_ROOT": "FALSE", "TRACK_UNDECIDED": "TRUE"}
NO_UNDECIDED = {"KEEP_LINKED": "TRUE", "ROOT_BY_ROOT": "TRUE", "TRACK_UNDECIDED": "FALSE"}
# name: (layout, series toggles, fixes off, invariants, expectation, overrides)
PROP_CONFIGS = {}
for lay in ["chain", "peers", "locked", "parentcand", "crossbind", "propns"]:
    # the series: mainline's checks (the victims are the maximal non-revealing
    # non-shifting subset, the structure, the covers) plus the claims of the hand-back
    PROP_CONFIGS[f"{lay}_order_fixed"] = (lay, SERIES, [], PROP_SAFETY, "pass", {})
    # the same fork with the toggles off is kernel/mount: the same state counts
    PROP_CONFIGS[f"{lay}_order_mainline"] = (lay, MAINLINE, [], PROP_MAINLINE_SAFETY, "pass", {})
# mainline's order, children first: the claim fails as soon as a committed
# copy has a child in the set; the set stays linked but is spliced in commit
# order: the same
for lay in ["propns", "chain", "peers", "locked"]:
    PROP_CONFIGS[f"{lay}_order_mainline_handback"] = (lay, MAINLINE, [], ["HandbackOK"], "violation: HandbackOK, the committed copies come children first" if lay == "propns" else "violation: HandbackOK, the committed copies come children first (if a copy with a child is reached within the budget)", {})
PROP_CONFIGS["propns_order_keep_splice"] = ("propns", KEEP_SPLICE, [], PROP_MAINLINE_SAFETY, "pass", {})
PROP_CONFIGS["propns_order_keep_splice_handback"] = ("propns", KEEP_SPLICE, [], ["HandbackOK"], "violation: HandbackOK, leaving the set linked does not order it, the walk does", {})
# trim_one() without the undecided flag: an ancestor is committed while its
# candidate child is undecided, the child is kept back later and stays
# attached to an unmounted parent
PROP_CONFIGS["crossbind_order_no_undecided"] = ("crossbind", NO_UNDECIDED, [], ["AlgebraOK", "Structure", "DeadUnderDead"], "violation: AlgebraOK or Structure, 6 is unmounted with the surviving 7 inside it", {})
# the mainline mutations still fire through the fork: handle_locked() on the
# locked layout, trim_ancestors() on the cross-bind layout (as in kernel/mount,
# the locked and chain layouts do not reach a trimmed ancestor within three
# operations, so locked_order_no_trim passes like locked_no_trim there)
PROP_CONFIGS["locked_order_no_handle_locked"] = ("locked", SERIES, ["FIX_HANDLE_LOCKED"], ["AlgebraOK", "CoverOK"], "violation", {})
PROP_CONFIGS["locked_order_no_trim"] = ("locked", SERIES, ["FIX_TRIM_ANCESTORS"], ["AlgebraOK", "Structure"], "pass", {})
PROP_CONFIGS["crossbind_order_no_trim"] = ("crossbind", SERIES, ["FIX_TRIM_ANCESTORS"], ["AlgebraOK", "Structure"], "violation", {})
# witnesses: several roots (two receiving namespaces), a member of the
# original set moved behind a committed ancestor, a surviving overmount
# reparented, propagated copies kept connected
PROP_CONFIGS["chain_order_witness_multiroot"] = ("chain", SERIES, [], ["NoMultiRoot"], "violation", {})
PROP_CONFIGS["parentcand_order_witness_umoved"] = ("parentcand", SERIES, [], ["NoUMoved"], "violation", {})
PROP_CONFIGS["locked_order_witness_reparent"] = ("locked", SERIES, [], ["NoReparent"], "violation", {})
PROP_CONFIGS["locked_order_witness_connected"] = ("locked", SERIES, [], ["NoConnected"], "violation", {})
for name, (layout, toggles, off, invs, expect, over) in PROP_CONFIGS.items():
    nmnt, nns, ops, fds = PROP_LAYOUTS[layout]
    ops = over.get("ops", ops)
    lines = [f"\\* generated by gen-cfgs.py: layout {layout} (the series' propagate_umount()), expected: {expect}",
             "SPECIFICATION Spec", "CONSTANTS",
             f"  MntIds = {{{', '.join(str(i) for i in range(1, nmnt + 1))}}}",
             f"  NsIds = {{{', '.join(str(i) for i in range(1, nns + 1))}}}",
             "  Sbs <- SbsDef", "  Dentries <- DentriesDef", "  DSb <- DSbDef",
             "  DParent <- DParentDef", "  SbRoot <- SbRootDef",
             "  Procs <- ProcsDef", "  ProcUser <- ProcUserDef",
             '  InitSb = "N"', '  RootSb = "R"', "  MountSbs <- MountSbsDef",
             f"  MaxOps = {ops}", f"  MaxFds = {fds}", "  Prelude <- PreludeDef"]
    for f in PROP_FIXES:
        lines.append(f"  {f} = {'FALSE' if f in off else 'TRUE'}")
    for c in ["KEEP_LINKED", "ROOT_BY_ROOT", "TRACK_UNDECIDED"]:
        lines.append(f"  {c} = {toggles[c]}")
    lines.append(f"  CHECK_DOC = {'TRUE' if over.get('doc') else 'FALSE'}")
    lines.append(f"  FAILS = {over.get('fails', 0)}")
    lines.append("INVARIANTS")
    lines += [f"  {i}" for i in invs]
    (here / f"{name}.cfg").write_text("\n".join(lines) + "\n")

print(f"{len(MW_CONFIGS) + len(VAC_CONFIGS) + len(PROP_CONFIGS)} configurations written")
