----------------------------- MODULE MC_full -----------------------------
(* The layout for MntPut: the umounter, a walker and a holder of each mount; two CPUs. *)
(* Generated by gen-cfgs.py. *)
EXTENDS MntPut, TLC

TaskListDef == <<"U", "HA", "WA", "HB", "WB">>
TaskMountDef == ("HA" :> "A") @@ ("WA" :> "A") @@ ("HB" :> "B") @@ ("WB" :> "B")
OrderAB == <<"A", "B">>
OrderBA == <<"B", "A">>
=============================================================================
