----------------------------- MODULE MC_hwa -----------------------------
(* The layout for MntPut: the umounter, a holder of A and a walker of A, which can reach A as the holder's fs->pwd (ViaPwd); nothing else touches B; two CPUs. *)
(* Generated by gen-cfgs.py. *)
EXTENDS MntPut, TLC

TaskListDef == <<"U", "HA", "WA">>
TaskMountDef == ("HA" :> "A") @@ ("WA" :> "A")
OrderAB == <<"A", "B">>
OrderBA == <<"B", "A">>
=============================================================================
