----------------------------- MODULE MC_hw -----------------------------
(* The layout for MntPut: the umounter, a holder of A, a walker of B; two CPUs. *)
(* Generated by gen-cfgs.py. *)
EXTENDS MntPut, TLC

TaskListDef == <<"U", "HA", "WB">>
TaskMountDef == ("HA" :> "A") @@ ("WB" :> "B")
OrderAB == <<"A", "B">>
OrderBA == <<"B", "A">>
=============================================================================
