----------------------------- MODULE MC_ww -----------------------------
(* The layout for MntPut: the umounter, a walker of A and a walker of B; two CPUs. *)
(* Generated by gen-cfgs.py. *)
EXTENDS MntPut, TLC

TaskListDef == <<"U", "WA", "WB">>
TaskMountDef == ("WA" :> "A") @@ ("WB" :> "B")
OrderAB == <<"A", "B">>
OrderBA == <<"B", "A">>
=============================================================================
