----------------------------- MODULE MC_w -----------------------------
(* The layout for MntPut: the umounter and a walker of A; nothing else touches B; two CPUs. *)
(* Generated by gen-cfgs.py. *)
EXTENDS MntPut, TLC

TaskListDef == <<"U", "WA">>
TaskMountDef == ("WA" :> "A")
OrderAB == <<"A", "B">>
OrderBA == <<"B", "A">>
=============================================================================
