----------------------------- MODULE MC_hh -----------------------------
(* The layout for MntPut: the umounter, a holder of A and a holder of B; two CPUs. *)
(* Generated by gen-cfgs.py. *)
EXTENDS MntPut, TLC

TaskListDef == <<"U", "HA", "HB">>
TaskMountDef == ("HA" :> "A") @@ ("HB" :> "B")
OrderAB == <<"A", "B">>
OrderBA == <<"B", "A">>
=============================================================================
