----------------------------- MODULE MC_h -----------------------------
(* The layout for MntPut: the umounter and a holder of A; nothing else touches B; two CPUs. *)
(* Generated by gen-cfgs.py. *)
EXTENDS MntPut, TLC

TaskListDef == <<"U", "HA">>
TaskMountDef == ("HA" :> "A")
OrderAB == <<"A", "B">>
OrderBA == <<"B", "A">>
=============================================================================
