----------------------------- MODULE MC_wh -----------------------------
(* The layout for MntPut: the umounter, a walker of A, a holder of B; two CPUs. *)
(* Generated by gen-cfgs.py. *)
EXTENDS MntPut, TLC

TaskListDef == <<"U", "WA", "HB">>
TaskMountDef == ("WA" :> "A") @@ ("HB" :> "B")
OrderAB == <<"A", "B">>
OrderBA == <<"B", "A">>
=============================================================================
